-- CREATE DATABASE `sewa` /*!40100 DEFAULT CHARACTER SET utf8 */;

set foreign_key_checks=0;

DROP TABLE IF exists category;
CREATE TABLE `category` (
  `categoryid` int(11) NOT NULL AUTO_INCREMENT,
  `category_name` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`categoryid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF exists subcategory;
CREATE TABLE `subcategory` (
  `subcategoryid` INT NOT NULL AUTO_INCREMENT,
  `subcategory_name` VARCHAR(255) NULL,
  `categoryid` INT NOT NULL,
  PRIMARY KEY (`subcategoryid`),
  INDEX `categoryid_idx` (`categoryid` ASC),
  CONSTRAINT `categoryid`
    FOREIGN KEY (`categoryid`)
    REFERENCES `category` (`categoryid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

DROP TABLE IF exists user;
CREATE TABLE `user` (
  `userid` int(11) NOT NULL AUTO_INCREMENT,
  #`username` bigint(20) NOT NULL UNIQUE,
  `username` bigint(20) NOT NULL,
  `password` text NOT NULL,
  `name` varchar(150) DEFAULT NULL,
  `phone` varchar(50) DEFAULT NULL,
  `address` varchar(100) DEFAULT NULL,
  `area` varchar(100) NOT NULL,
  `city` varchar(100) NOT NULL,
  `state` varchar(100) NOT NULL,
  `country` varchar(100) NOT NULL,
  `postalcode` varchar(50) DEFAULT NULL,
  `coordinates` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`userid`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8;

DROP TABLE IF exists service;
CREATE TABLE `service` (
  `serviceid` INT NOT NULL AUTO_INCREMENT,
  `servicename` VARCHAR(255) NULL,
  `categoryid` INT NOT NULL,
  `subcategoryid` INT NULL,
  `details` VARCHAR(255) NULL DEFAULT NULL,
  `userid` INT NULL,
  PRIMARY KEY (`serviceid`),
  INDEX `categoryid_idx` (`categoryid` ASC),
  INDEX `subcategoryid_idx` (`subcategoryid` ASC),
  INDEX `userid_idx` (`userid` ASC),
  CONSTRAINT `categoryid_fk`
    FOREIGN KEY (`categoryid`)
    REFERENCES `sewa`.`Category` (`categoryid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `subcategoryid_fk`
    FOREIGN KEY (`subcategoryid`)
    REFERENCES `sewa`.`SubCategory` (`subcategoryid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `userid_fk`
    FOREIGN KEY (`userid`)
    REFERENCES `sewa`.`user` (`userid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

DROP TABLE IF exists job;
CREATE TABLE `job` (
  `jobid` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `details` VARCHAR(255) NULL,
  `serviceid` INT NOT NULL,
  PRIMARY KEY (`jobid`),
  INDEX `serviceid_idx` (`serviceid` ASC),
  CONSTRAINT `serviceid_fk`
    FOREIGN KEY (`serviceid`)
    REFERENCES `sewa`.`service` (`serviceid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

DROP TABLE IF EXISTS country;
CREATE TABLE `country` (
  `countryid` INT NOT NULL AUTO_INCREMENT,
  `countryname` VARCHAR(255) NULL,
  PRIMARY KEY (`countryid`));


DROP TABLE IF exists state;
CREATE TABLE `state` (
  `stateid` int(11) NOT NULL AUTO_INCREMENT,
  `statename` varchar(255) NOT NULL,
  `countryid` int(11) NOT NULL,
  PRIMARY KEY (`stateid`),
  KEY `countryid_fk_idx` (`countryid`),
  CONSTRAINT `countryid_fk` FOREIGN KEY (`countryid`) REFERENCES `country` (`countryid`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF exists city;
CREATE TABLE `city` (
  `cityid` INT NOT NULL AUTO_INCREMENT,
  `cityname` VARCHAR(255) NOT NULL,
  `stateid` INT NOT NULL,
  PRIMARY KEY (`cityid`),
  INDEX `stateid_fk_idx` (`stateid` ASC),
  CONSTRAINT `stateid_fk`
    FOREIGN KEY (`stateid`)
    REFERENCES `sewa`.`state` (`stateid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

DROP TABLE IF exists area;
CREATE TABLE `area` (
  `areaid` INT NOT NULL AUTO_INCREMENT,
  `areaname` VARCHAR(255) NULL,
  `cityid` INT NOT NULL,
  PRIMARY KEY (`areaid`),
  INDEX `cityid_fk_idx` (`cityid` ASC),
  CONSTRAINT `cityid_fk`
    FOREIGN KEY (`cityid`)
    REFERENCES `sewa`.`city` (`cityid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

-- Data
INSERT INTO `country` (`countryname`) VALUES ('India'), ('US'), ('China'), ('Canada');

INSERT INTO `state` ( `statename`,`countryid`) VALUES
('ANDHRA PRADESH',1),
('ASSAM',1),
('ARUNACHAL PRADESH',1),
('BIHAR',1),
('GUJRAT',1),
('HARYANA',1),
('HIMACHAL PRADESH',1),
('JAMMU & KASHMIR',1),
('KARNATAKA',1),
('KERALA',1),
('MADHYA PRADESH',1),
('MAHARASHTRA',1),
('MANIPUR',1),
('MEGHALAYA',1),
('MIZORAM',1),
('NAGALAND',1),
('ORISSA',1),
('PUNJAB',1),
('RAJASTHAN',1),
('SIKKIM',1),
('TAMIL NADU',1),
('TRIPURA',1),
('UTTAR PRADESH',1),
('WEST BENGAL',1),
('DELHI',1),
('GOA',1),
('PONDICHERY',1),
('LAKSHDWEEP',1),
('DAMAN & DIU',1),
('DADRA & NAGAR',1),
('CHANDIGARH',1),
('ANDAMAN & NICOBAR',1),
('UTTARANCHAL',1),
('JHARKHAND',1),
('CHATTISGARH',1);

INSERT INTO `city` ( `cityname`,`stateid`) VALUES
('Mumbai', 12),
('Pune', 12),
('Kolhapur', 12),
('Nagpur', 12),
('Sangli', 12),
('Satara', 12),
('Jalgaon', 12),
('Latur', 12),
('Aurangabad', 12),
('Beed', 12),
('Usmanabad', 12),
('Solapur', 12),
('Karad', 12),
('Ratnagiri', 12),
('Dapoli', 12),
('Alibaug', 12);

INSERT INTO `area` ( `areaname`,`cityid`) VALUES
('Bavdhan', 2),
('Kothrud', 2),
('Swargate', 2),
('Katraj', 2),
('Dhankawadi', 2),
('Indiranagar', 2),
('Mayur Colony', 2),
('Hingane', 2),
('Ambegaon', 2),
('Erandawane', 2),
('Paud Road', 2),
('Karvenagar', 2),
('Waraje', 2),
('Sadashiv Peth', 2),
('Narayan Peth', 2),
('Tilak Road', 2);

INSERT INTO `category` ( `category_name`) VALUES
('Arts, crafts, and collectibles'),
('Baby'),
('Beauty and fragrances'),
('Books and magazines'),
('Business to business'),
('Clothing, accessories, and shoes'),
('Computers, accessories, and services'),
('Education'),
('Electronics and telecom'),
('Entertainment and media'),
('Financial services and products'),
('Food retail and service'),
('Gifts and flowers'),
('Government'),
('Health and personal care'),
('Home and garden'),
('Nonprofit'),
('Pets and animals'),
('Religion and spirituality'),
('Retail'),
('Services - other'),
('Sports and outdoors'),
('Toys and hobbies'),
('Travel'),
('Vehicle sales'),
('Vehicle service and accessories');


INSERT INTO `subcategory` ( `subcategory_name`,`categoryid`) VALUES
('Antiques',1),
('Art and craft supplies',1),
('Art dealers and galleries',1),
('Camera and photographic supplies',1),
('Digital art',1),
('Memorabilia',1),
('Music store (instruments and sheet music)',1),
('Sewing, needlework, and fabrics',1),
('Stamp and coin',1),
('Stationary, printing and writing paper',1),
('Vintage and collectibles',1),
('Clothing',2),
('Furniture',2),
('Baby products (other)',2),
('Safety and health',2),
('Bath and body',3),
('Fragrances and perfumes',3),
('Makeup and cosmetics',3),
('Audio books',4),
('Digital content',4),
('Educational and textbooks',4),
('Fiction and nonfiction',4),
('Magazines',4),
('Publishing and printing',4),
('Rare and used books',4),
('Accounting',5),
('Advertising',5),
('Agricultural',5),
('Architectural, engineering, and surveying services',5),
('Chemicals and allied products',5),
('Commercial photography, art, and graphics',5),
('Construction',5),
('Consulting services',5),
('Educational services',5),
('Equipment rentals and leasing services',5),
('Equipment repair services',5),
('Hiring services',5),
('Industrial and manufacturing supplies',5),
('Mailing lists',5),
('Marketing',5),
('Multi-level marketing',5),
('Office and commercial furniture',5),
('Office supplies and equipment',5),
('Publishing and printing',5),
('Quick copy and reproduction services',5),
('Shipping and packing',5),
('Stenographic and secretarial support services',5),
('Wholesale',5),
('Children\'s clothing',6),
('Men\'s clothing',6),
('Women\'s clothing',6),
('Shoes',6),
('Military and civil service uniforms',6),
('Accessories',6),
('Retail (fine jewelry and watches)',6),
('Wholesale (precious stones and metals)',6),
('Fashion jewelry',6),
('Computer and data processing services',7),
('Desktops, laptops, and notebooks',7),
('Digital content',7),
('eCommerce services',7),
('Maintenance and repair services',7),
('Monitors and projectors',7),
('Networking',7),
('Online gaming',7),
('Parts and accessories',7),
('Peripherals',7),
('Software',7),
('Training services',7),
('Web hosting and design',7),
('Business and secretarial schools',8),
('Child daycare services',8),
('Colleges and universities',8),
('Dance halls, studios, and schools',8),
('Elementary and secondary schools',8),
('Vocational and trade schools',8),
('Cameras, camcorders, and equipment',9),
('Cell phones, PDAs, and pagers',9),
('General electronic accessories',9),
('Home audio',9),
('Home electronics',9),
('Security and surveillance',9),
('Telecommunication equipment and sales',9),
('Telecommunication services',9),
('Telephone cards',9),
('Memorabilia',10),
('Movie tickets',10),
('Movies (DVDs, videotapes)',10),
('Music (CDs, cassettes and albums)',10),
('Cable, satellite, and other pay TV and radio',10),
('Adult digital content',10),
('Concert tickets',10),
('Theater tickets',10),
('Toys and games',10),
('Slot machines',10),
('Digital content',10),
('Entertainers',10),
('Gambling',10),
('Online games',10),
('Video games and systems',10),
('Accounting',11),
('Collection agency',11),
('Commodities and futures exchange',11),
('Consumer credit reporting agencies',11),
('Debt counseling service',11),
('Credit union',11),
('Currency dealer and currency exchange',11),
('Escrow',11),
('Finance company',11),
('Financial and investment advice',11),
('Insurance (auto and home)',11),
('Insurance (life and annuity)',11),
('Investments (general)',11),
('Money service business',11),
('Mortgage brokers or dealers',11),
('Online gaming currency',11),
('Paycheck lender or cash advance',11),
('Prepaid and stored value cards',11),
('Real estate agent',11),
('Remittance',11),
('Rental property management',11),
('Security brokers and dealers',11),
('Wire transfer and money order',11),
('Alcoholic beverages',12),
('Catering services',12),
('Coffee and tea',12),
('Gourmet foods',12),
('Specialty and miscellaneous food stores',12),
('Restaurant',12),
('Tobacco',12),
('Vitamins and supplements',12),
('Florist',13),
('Gift, card, novelty, and souvenir shops',13),
('Gourmet foods',13),
('Nursery plants and flowers',13),
('Party supplies',13),
('Government services (not elsewhere classified)',14),
('Drugstore (excluding prescription drugs)',15),
('Drugstore (including prescription drugs)',15),
('Dental care',15),
('Medical care',15),
('Medical equipment and supplies',15),
('Vision care',15),
('Vitamins and supplements',15),
('Antiques',16),
('Appliances',16),
('Art dealers and galleries',16),
('Bed and bath',16),
('Construction material',16),
('Drapery, window covering, and upholstery',16),
('Exterminating and disinfecting services',16),
('Fireplace, and fireplace screens',16),
('Furniture',16),
('Garden supplies',16),
('Glass, paint, and wallpaper',16),
('Hardware and tools',16),
('Home decor',16),
('Housewares',16),
('Kitchenware',16),
('Landscaping',16),
('Rugs and carpets',16),
('Security and surveillance equipment',16),
('Swimming pools and spas',16),
('Charity',17),
('Political',17),
('Religious',17),
('Other',17),
('Personal',17),
('Educational',17),
('Medication and supplements',18),
('Pet shops, pet food, and supplies',18),
('Specialty or rare pets',18),
('Veterinary services',18),
('Membership services',19),
('Merchandise',19),
('Services (not elsewhere classified)',19),
('Chemicals and allied products',20),
('Department store',20),
('Discount store',20),
('Durable goods',20),
('Non-durable goods',20),
('Used and secondhand store',20),
('Variety store',20),
('Advertising',21),
('Shopping services and buying clubs',21),
('Career services',21),
('Carpentry',21),
('Plumbing',21),
('Child care services',21),
('Cleaning and maintenance',21),
('Commercial photography',21),
('Computer and data processing services',21),
('Computer network services',21),
('Consulting services',21),
('Counseling services',21),
('Courier services',21),
('Dental care',21),
('eCommerce services',21),
('Electrical and small appliance repair',21),
('Entertainment',21),
('Equipment rental and leasing services',21),
('Event and wedding planning',21),
('Gambling',21),
('General contractors',21),
('Graphic and commercial design',21),
('Health and beauty spas',21),
('IDs, licenses, and passports',21),
('Importing and exporting',21),
('Information retrieval services',21),
('Insurance - auto and home',21),
('Insurance - life and annuity',21),
('Landscaping and horticultural',21),
('Legal services and attorneys',21),
('Local delivery service',21),
('Lottery and contests',21),
('Medical care',21),
('Membership clubs and organizations',21),
('Misc. publishing and printing',21),
('Moving and storage',21),
('Online dating',21),
('Photofinishing',21),
('Photographic studios - portraits',21),
('Protective and security services',21),
('Quick copy and reproduction services',21),
('Radio, television, and stereo repair',21),
('Real estate agent',21),
('Rental property management',21),
('Reupholstery and furniture repair',21),
('Services (not elsewhere classified)',21),
('Shipping and packing',21),
('Swimming pool services',21),
('Tailors and alterations',21),
('Telecommunication service',21),
('Utilities',21),
('Vision care',21),
('Watch, clock, and jewelry repair',21),
('Athletic shoes',22),
('Bicycle shop, service, and repair',22),
('Boating, sailing and accessories',22),
('Camping and outdoors',22),
('Dance halls, studios, and schools',22),
('Exercise and fitness',22),
('Fan gear and memorabilia',22),
('Firearm accessories',22),
('Firearms',22),
('Hunting',22),
('Knives',22),
('Martial arts weapons',22),
('Sport games and toys',22),
('Sporting equipment',22),
('Swimming pools and spas',22),
('Arts and crafts',23),
('Camera and photographic supplies',23),
('Hobby, toy, and game shops',23),
('Memorabilia',23),
('Music store - instruments and sheet music',23),
('Stamp and coin',23),
('Stationary, printing, and writing paper',23),
('Vintage and collectibles',23),
('Video games and systems',23),
('Airline',24),
('Auto rental',24),
('Bus line',24),
('Cruises',24),
('Lodging and accommodations',24),
('Luggage and leather goods',24),
('Recreational services',24),
('Sporting and recreation camps',24),
('Taxicabs and limousines',24),
('Timeshares',24),
('Tours',24),
('Trailer parks or campgrounds',24),
('Transportation services - other',24),
('Travel agency',24),
('Auto dealer - new and used',25),
('Auto dealer - used only',25),
('Aviation',25),
('Boat dealer',25),
('Mobile home dealer',25),
('Motorcycle dealer',25),
('Recreational and utility trailer dealer',25),
('Recreational vehicle dealer',25),
('Vintage and collectibles',25),
('New parts and supplies - motor vehicle',26),
('Used parts - motor vehicle',26),
('Audio and video',26),
('Auto body repair and paint',26),
('Auto rental',26),
('Auto service',26),
('Automotive tire supply and service',26),
('Boat rental and leases',26),
('Car wash',26),
('Motor home and recreational vehicle rental',26),
('Tools and equipment',26),
('Towing service',26),
('Truck and utility trailer rental',26),
('Accessories',26);

set foreign_key_checks=1;